#!/bin/bash

function printUsage() {
    echo "Usage:"
    echo "$0 <GraalVM launcher> <launcher args>"
    echo "Example:"
    echo "$0 js example.js"
    exit 0
}

[ -z "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ] && printUsage

LAUNCHER=$1
shift

"$GRAALVM_HOME/bin/$LAUNCHER" \
    --jvm \
    --vm.Dtruffle.class.path.append=graalvm/target/pinpoint-graal-agent-0.0.1-jar-with-dependencies.jar \
    --pinpoint-profiler \
    "$@"

#--vm.Dtruffle.instrumentation.trace=true \
#--vm.Dpolyglotimpl.DebugMissingClose=true \